---

name: dendro
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pytorch
  - heat
  - matplotlib
  - jupyter
  - jupytext
  - pytest
  - coverage
  - black
  - ruff
  - numba

  - pip
  - pip:
    - astrodendro
    - pre-commit
    - pytest-isolate-mpi
